apiVersion: apps/v1
kind: Deployment
metadata:
  name: bts-server
  labels:
    app: bts-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bts-server
  template:
    metadata:
      labels:
        app: bts-server
    spec:
      containers:
      - image: europe-north1-docker.pkg.dev/steel-climber-303808/btscontainer/bts-server:latest
        name: bts-server
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
